system:
    default:
        field_templates:
            - { template: "GothEzPlatformSoundCloudFieldTypeBundle:fields:goth_soundcloud.html.twig", priority: 0 }
        fielddefinition_settings_templates:
            - { template: "GothEzPlatformSoundCloudFieldTypeBundle:platformui/content_type/view:goth_soundcloud.html.twig", priority: 0 }
        fielddefinition_edit_templates:
            - { template: "GothEzPlatformSoundCloudFieldTypeBundle:platformui/content_type/edit:goth_soundcloud.html.twig", priority: 0 }